import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.STELLARIS_PLAYWRIGHT_PATH ? pathToFileURL(process.env.STELLARIS_PLAYWRIGHT_PATH).href : 'playwright');
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('verification',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.locator('.story-card').first().waitFor();
await page.screenshot({path:'verification/desktop.png',fullPage:false});
const first=await page.locator('.access').getAttribute('data-open');
await page.locator('.access').click();await page.locator('#reader-title').waitFor();
const chinese=await page.locator('#reader-title').innerText();
await page.locator('#reader-language').click();
const english=await page.locator('#reader-title').innerText();
if(chinese===english)throw new Error('Language did not switch');
await page.locator('#reader-language').click();
await page.waitForTimeout(500);
await page.screenshot({path:'verification/reader.png',fullPage:false});
await page.locator('.choice>summary').first().click();
await page.locator('[data-open="special_projects:HORIZON_SIGNAL_PROJECT"]').click();
await page.locator('#reader-title').waitFor();
await page.locator('.continuations [data-open="akx.9001"]').click();
await page.waitForFunction(()=>document.querySelector('#reader-title')?.textContent.includes('引力'));
if(await page.locator('.choice').count()!==2)throw new Error('Original branching options missing');
await page.locator('#reader-back').click();
await page.waitForFunction(()=>location.hash.includes('HORIZON_SIGNAL_PROJECT'));
await page.locator('#reader-back').click();
await page.waitForFunction(()=>location.hash.includes('akx.9000'));
await page.locator('#close-reader').click();
await page.locator('#search').fill('anomaly.1');
await page.waitForTimeout(200);
if(!(await page.locator('.story-card').count()))throw new Error('Search returned no records');
await page.locator('#search').fill('THIS_CANNOT_EXIST_748392');await page.waitForTimeout(200);
await page.locator('#clear-search').waitFor();await page.locator('#clear-search').click();
await page.locator('[data-category="crisis"]').click();
if(!(await page.locator('.story-card').count()))throw new Error('Category empty');
await page.locator('#next-page').click();
if(!(await page.locator('#page-status').innerText()).startsWith('2 /'))throw new Error('Pagination failed');
await page.locator('#motion').click();
if(!(await page.locator('html').getAttribute('class')).includes('reduced-motion'))throw new Error('Reduced motion failed');
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});await page.locator('.story-card').first().waitFor();
await page.screenshot({path:'verification/mobile.png',fullPage:false});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw new Error('Mobile horizontal overflow');
await page.locator('.access').click();await page.locator('#reader-title').waitFor();
await page.screenshot({path:'verification/mobile-reader.png',fullPage:false});
await page.keyboard.press('Escape');
if(await page.locator('#reader').evaluate(el=>el.open))throw new Error('Escape did not close reader');
await page.goto('http://127.0.0.1:4173/#record='+encodeURIComponent(first),{waitUntil:'networkidle'});
await page.locator('#reader-title').waitFor();
await writeFile('verification/browser-results.json',JSON.stringify({desktop:[1440,1000],mobile:[390,844],chinese,english,deepLink:first,mobileOverflow:overflow,errors,checks:['index loads','reader opens','bilingual switch','event → project → event','two-step path backtracking','search','empty state','categories','pagination','reduced motion','mobile layout','escape','deep link']},null,2));
await browser.close();if(errors.length)throw new Error(errors.join('\n'));console.log('Visual smoke tests passed.');
